AppBundle\Entity\Tbldisks:
    type: entity
    table: tbldisks
    indexes:
        CopyID:
            columns:
                - CopyID
        VolumeID:
            columns:
                - VolumeID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        volumeid:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: VolumeID
        copyid:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: CopyID
        descriptiontxt:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: DescriptionTxt
        locationtxt:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: LocationTxt
    lifecycleCallbacks: {  }
