<?php

namespace AppBundle\Repository;

/**
 * SymProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SymProductRepository extends \Doctrine\ORM\EntityRepository
{
}
